[project]
name = "prompts"
version = "0.0.0-9001"
description = "A package for notetaking inspired by the zettelkasten method"
readme = "README.md"
dependencies = ['typer', 'python-frontmatter']
[project.scripts]
qp = "qp.cli:app"
